#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}
ip=${SSH_CLIENT:-$(ip)}

print_columns "Logged as" "${user}@${hostname} (connected from: ${ip})"
