#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}
ip="$SSH_CLIENT | awk '{ print $1}'"
ip=${ip:-$(ip)}

print_columns "Logged as" "${user}@${hostname} (connected from: ${ip})"
