#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=../framework.sh
source "${BASE_DIR}/framework.sh"

ip_v4=$(dig +short txt ch whoami.cloudflare @1.0.0.1 | tr -d '"')

text=$(print_wrap "${WIDTH}" "${ip_v4}")

print_columns "Public IP" "${text}"
