#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=../framework.sh
source "${BASE_DIR}/framework.sh"

PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
PROCESS_ALL=$(echo "$PROCESS" | awk '{print $2}' | awk '{ SUM += $1} END { print SUM }')
PROCESS_ROOT=$(echo "$PROCESS" | grep root | awk '{print $2}')
PROCESS_USER=$(echo "$PROCESS" | grep -v root | awk '{print $2}' | awk '{ SUM += $1} END { print SUM }')
user=${USER:-$(id -un)}

processes="${CN}${PROCESS_ROOT} ${CW}(root), ${CN}${PROCESS_USER} ${CO}(${user}), ${CN}${PROCESS_ALL} ${CA}(total)"

print_columns "Processes" "${processes}"
